export const ONE_COURSE_DETAILS_REQUEST = "ONE_COURSE_DETAILS_REQUEST";
export const ONE_COURSE_DETAILS_SUCCESS = "ONE_COURSE_DETAILS_SUCCESS";
export const ONE_COURSE_DETAILS_FAILS = "ONE_COURSE_DETAILS_FAILS";

export const ALL_USER_COURSES_REQUEST = "ALL_USER_COURSES_REQUEST";
export const ALL_USER_COURSES_SUCCESS = "ALL_USER_COURSES_SUCCESS";
export const ALL_USER_COURSES_FAILS = "ALL_USER_COURSES_FAILS";
