export const ONE_COURSE_DETAILS_REQUEST = "ONE_COURSE_DETAILS_REQUEST";
export const ONE_COURSE_DETAILS_SUCCESS = "ONE_COURSE_DETAILS_SUCCESS";
export const ONE_COURSE_DETAILS_FAILS = "ONE_COURSE_DETAILS_FAILS";
